on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
        description: "Location of Terragrunt files for execution"
        default: ./
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  apply:
    name: Terraform Apply
    runs-on:
      - self-hosted
      - terraform-1.0
    needs: validate
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terragrunt apply
        run: terragrunt apply -auto-approve --terragrunt-working-dir ${{ inputs.workingDirectory }}
        env:
          ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
